version: '2.1'
services:
  producer:
    build: .
    image: us.icr.io/skills-network/slack-nats-consumer:ci
    working_dir: /app
    user: "node"
    environment:
      - NODE_ENV=production
    command: 'npm start'
