apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-nats-consumer.fullname" . }}
  labels:
    {{- include "template-nats-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "template-nats-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template-nats-consumer.selectorLabels" . | nindent 8 }}
    spec:
    {{- range .Values.imageRegistries }}
      imagePullSecrets:
      - name: {{ .name | quote }}
    {{- end }}
      serviceAccountName: {{ include "template-nats-consumer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "bin/probe"
          readinessProbe:
            exec:
              command:
                - "bin/probe"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $val := .Values.nats }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
