{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template-nats-consumer.serviceAccountName" . }}
  labels:
{{ include "template-nats-consumer.labels" . | nindent 4 }}
{{- end -}}
